### ISSUE TITLE
Chaining server side 

### ISSUE THREAD

**Issue by pociej** [deanius/deanius-meteor-promise#7]
Hi @chicagogrooves , idea is nice but it doesnt work server side because of Meteor.bindEnvironment. 
Lets try your example server side : 
```
Meteor.promise("createCustomer", "foo@bar.com", "VISA")
  .then(Meteor.bindEnvironment(function(customer) {
    return Meteor.promise("createCustomerSubscription", customer.id, plan);
  }))
  .then(Meteor.bindEnvironment(function(plan) {
    console.log("Plan", plan);
  }))
  .catch(Meteor.bindEnvironment(function (err) {
    console.error(err);
  })) 
```

what we can see ? in third promise plan is undefined , it is called before any output from ```createCustomerSubscription```.

**Comment by chicagogrooves** [comment]
Hmm, I know I set the package up to be client and server, but I wonder if I should reconsider that now. 

The reason being - it's strange to make a method call from the server side, the approach described here shows how to maintain a method that can be called directly - without `Meteor.call`, or `Meteor.promise`.
http://stackoverflow.com/questions/23188424/meteorjs-meteor-methods-call-from-server-to-server

What do you think- if you want to try to support your use case from the server, let me know a bit more, maybe create a failing test in a PR ?

**Comment by pociej** [comment]
@deanius , yep i know that it is strange to call methods from server to server (anyway in tutorial , you called 'inspiration' they calling methods server side ;) ) , but it is detail. 
You can easy change you package and call server side defined functions instead of methods, youwill have same problem , Imo meteor needs own implementation of server side promises . 
In regards to the cleint side usage of package it is also strange , calling meteor methods one after another generates unnecessary client-server ping pong . In most cases you want to call one method which chain few tasks server side and wait for response . But to do that you need server side implementation of promises ( or use other tool ).

**Comment by deanius** [comment]
Meteor's support for ES6 (including Promises, I assume), in version 1.2 may make this package obsolete-  we'll see what they come up with.. Thanks for your very valid points!
